//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.WHTCalcEntryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WHTCalcEntryService.IWHTCalcEntryService")]
    public interface IWHTCalcEntryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWHTCalcEntryService/GetCalcEntry", ReplyAction="http://tempuri.org/IWHTCalcEntryService/GetCalcEntryResponse")]
        System.Data.DataTable GetCalcEntry();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWHTCalcEntryServiceChannel : TestApp.WHTCalcEntryService.IWHTCalcEntryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WHTCalcEntryServiceClient : System.ServiceModel.ClientBase<TestApp.WHTCalcEntryService.IWHTCalcEntryService>, TestApp.WHTCalcEntryService.IWHTCalcEntryService {
        
        public WHTCalcEntryServiceClient() {
        }
        
        public WHTCalcEntryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WHTCalcEntryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WHTCalcEntryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WHTCalcEntryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetCalcEntry() {
            return base.Channel.GetCalcEntry();
        }
    }
}
