//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Razer.RazerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RazerService.IRazerService")]
    public interface IRazerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/GetObject", ReplyAction="http://tempuri.org/IRazerService/GetObjectResponse")]
        System.Data.DataSet GetObject(string BusinessObjectName, System.Data.DataSet Parms, System.Data.DataSet SecurityRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/GetObject", ReplyAction="http://tempuri.org/IRazerService/GetObjectResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetObjectAsync(string BusinessObjectName, System.Data.DataSet Parms, System.Data.DataSet SecurityRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/GetTableObject", ReplyAction="http://tempuri.org/IRazerService/GetTableObjectResponse")]
        System.Data.DataSet GetTableObject(string BusinessObjectName, System.Data.DataSet Parms, string TableName, System.Data.DataSet SecurityRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/GetTableObject", ReplyAction="http://tempuri.org/IRazerService/GetTableObjectResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetTableObjectAsync(string BusinessObjectName, System.Data.DataSet Parms, string TableName, System.Data.DataSet SecurityRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/SaveObject", ReplyAction="http://tempuri.org/IRazerService/SaveObjectResponse")]
        System.Data.DataSet SaveObject(string BusinessObjectName, System.Data.DataSet ObjectData, System.Data.DataSet SecurityRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/SaveObject", ReplyAction="http://tempuri.org/IRazerService/SaveObjectResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SaveObjectAsync(string BusinessObjectName, System.Data.DataSet ObjectData, System.Data.DataSet SecurityRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/SaveTableObject", ReplyAction="http://tempuri.org/IRazerService/SaveTableObjectResponse")]
        System.Data.DataSet SaveTableObject(string BusinessObjectName, System.Data.DataSet ObjectData, string TableName, System.Data.DataSet SecurityRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/SaveTableObject", ReplyAction="http://tempuri.org/IRazerService/SaveTableObjectResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SaveTableObjectAsync(string BusinessObjectName, System.Data.DataSet ObjectData, string TableName, System.Data.DataSet SecurityRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/NewObject", ReplyAction="http://tempuri.org/IRazerService/NewObjectResponse")]
        System.Data.DataSet NewObject(string BusinessObjectName, System.Data.DataSet Parms, System.Data.DataSet SecurityRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/NewObject", ReplyAction="http://tempuri.org/IRazerService/NewObjectResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> NewObjectAsync(string BusinessObjectName, System.Data.DataSet Parms, System.Data.DataSet SecurityRole);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/GetDatabaseServerName", ReplyAction="http://tempuri.org/IRazerService/GetDatabaseServerNameResponse")]
        string GetDatabaseServerName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRazerService/GetDatabaseServerName", ReplyAction="http://tempuri.org/IRazerService/GetDatabaseServerNameResponse")]
        System.Threading.Tasks.Task<string> GetDatabaseServerNameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRazerServiceChannel : Razer.RazerService.IRazerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RazerServiceClient : System.ServiceModel.ClientBase<Razer.RazerService.IRazerService>, Razer.RazerService.IRazerService {
        
        public RazerServiceClient() {
        }
        
        public RazerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RazerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RazerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RazerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetObject(string BusinessObjectName, System.Data.DataSet Parms, System.Data.DataSet SecurityRole) {
            return base.Channel.GetObject(BusinessObjectName, Parms, SecurityRole);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetObjectAsync(string BusinessObjectName, System.Data.DataSet Parms, System.Data.DataSet SecurityRole) {
            return base.Channel.GetObjectAsync(BusinessObjectName, Parms, SecurityRole);
        }
        
        public System.Data.DataSet GetTableObject(string BusinessObjectName, System.Data.DataSet Parms, string TableName, System.Data.DataSet SecurityRole) {
            return base.Channel.GetTableObject(BusinessObjectName, Parms, TableName, SecurityRole);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetTableObjectAsync(string BusinessObjectName, System.Data.DataSet Parms, string TableName, System.Data.DataSet SecurityRole) {
            return base.Channel.GetTableObjectAsync(BusinessObjectName, Parms, TableName, SecurityRole);
        }
        
        public System.Data.DataSet SaveObject(string BusinessObjectName, System.Data.DataSet ObjectData, System.Data.DataSet SecurityRole) {
            return base.Channel.SaveObject(BusinessObjectName, ObjectData, SecurityRole);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SaveObjectAsync(string BusinessObjectName, System.Data.DataSet ObjectData, System.Data.DataSet SecurityRole) {
            return base.Channel.SaveObjectAsync(BusinessObjectName, ObjectData, SecurityRole);
        }
        
        public System.Data.DataSet SaveTableObject(string BusinessObjectName, System.Data.DataSet ObjectData, string TableName, System.Data.DataSet SecurityRole) {
            return base.Channel.SaveTableObject(BusinessObjectName, ObjectData, TableName, SecurityRole);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SaveTableObjectAsync(string BusinessObjectName, System.Data.DataSet ObjectData, string TableName, System.Data.DataSet SecurityRole) {
            return base.Channel.SaveTableObjectAsync(BusinessObjectName, ObjectData, TableName, SecurityRole);
        }
        
        public System.Data.DataSet NewObject(string BusinessObjectName, System.Data.DataSet Parms, System.Data.DataSet SecurityRole) {
            return base.Channel.NewObject(BusinessObjectName, Parms, SecurityRole);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> NewObjectAsync(string BusinessObjectName, System.Data.DataSet Parms, System.Data.DataSet SecurityRole) {
            return base.Channel.NewObjectAsync(BusinessObjectName, Parms, SecurityRole);
        }
        
        public string GetDatabaseServerName() {
            return base.Channel.GetDatabaseServerName();
        }
        
        public System.Threading.Tasks.Task<string> GetDatabaseServerNameAsync() {
            return base.Channel.GetDatabaseServerNameAsync();
        }
    }
}
